### ISSUE TITLE
We have to organize templates and add another one for "after login" usage

### ISSUE THREAD

**Issue by Hgmoa** [Hgmoa/DesarrolloAplicacionesWeb#7]

**Comment by JorgeGalingP** [comment]
This is the template we use for our dashboard: https://demo.bootstrapious.com/dashboard/1-3-2/index.html

**Comment by CVelazquezURJC** [comment]
we have to swich or boostrap and use one from a CDN

**Comment by Hgmoa** [comment]
Will do that on a future update
